<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20221018102418 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE articulo (CODARTICULO INT AUTO_INCREMENT NOT NULL, CODIGOEAN VARCHAR(25) NOT NULL, REFERENCIAPROVEEDOR VARCHAR(20) DEFAULT NULL, REFERENCIAMARCA VARCHAR(20) DEFAULT NULL, DESCRIPCION VARCHAR(100) DEFAULT NULL, AUX_MARGEN NUMERIC(14, 4) DEFAULT NULL, MARGEN NUMERIC(14, 4) DEFAULT NULL, BASE NUMERIC(14, 4) DEFAULT NULL, EXISTENCIASDISPONIBLES NUMERIC(12, 2) DEFAULT NULL, PVP_OFERTA_MOSTRADOR NUMERIC(14, 4) DEFAULT NULL, PVP NUMERIC(14, 4) DEFAULT NULL, PVP2 NUMERIC(14, 4) DEFAULT NULL, CODIGO INT DEFAULT NULL, ESMANOOBRA TINYINT(1) DEFAULT NULL, UDS_ULTIMAENTRADA NUMERIC(10, 0) DEFAULT NULL, BASE2 NUMERIC(10, 0) DEFAULT NULL, FAVORITO TINYINT(1) DEFAULT NULL, POSIBLEB TINYINT(1) DEFAULT NULL, CODART_GRANEL VARCHAR(70) DEFAULT NULL, UD_X_UDGRANNEL NUMERIC(12, 2) DEFAULT NULL, IMAGEN BLOB DEFAULT NULL, IVAPERCENT NUMERIC(4, 2) DEFAULT NULL, NORDEN_MOSTRAR INT DEFAULT NULL, INTRASTAT VARCHAR(15) DEFAULT NULL, UMEDIDA VARCHAR(5) DEFAULT NULL, PESO NUMERIC(10, 0) DEFAULT NULL, REQ_EQ NUMERIC(10, 0) DEFAULT NULL, CODCATEGORIA INT DEFAULT NULL, CODSUBCATEGORIA INT DEFAULT NULL, IDWOOCOMMERCE INT DEFAULT NULL, CARACTECNICAS VARCHAR(90) DEFAULT NULL, PVD NUMERIC(14, 4) DEFAULT NULL, NOMCATEGORIA VARCHAR(30) DEFAULT NULL, NOMSUBCATEGORIA VARCHAR(100) DEFAULT NULL, CODPROVEEDOR INT DEFAULT NULL, CODSUBFAMILIA INT DEFAULT NULL, CODFAMILIA INT DEFAULT NULL, CODMARCAR INT DEFAULT NULL, INDEX ARTICULO_FK_1 (CODMARCAR), INDEX articulo_FK2 (CODPROVEEDOR), INDEX IDX_69E94E91819EFD6C (CODFAMILIA), INDEX articulo_FK3 (CODFAMILIA, CODSUBFAMILIA), INDEX articulo_FK (CODSUBFAMILIA, CODFAMILIA), PRIMARY KEY(CODARTICULO)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE familia (CODFAMILIA INT AUTO_INCREMENT NOT NULL, NOMBRE VARCHAR(40) DEFAULT NULL, MARGEN NUMERIC(10, 0) DEFAULT NULL, IVAPERCENT NUMERIC(10, 0) DEFAULT NULL, ESMANOOBRA TINYINT(1) DEFAULT NULL, INICIOCODEAN VARCHAR(2) DEFAULT NULL, RE NUMERIC(10, 0) DEFAULT NULL, IMAGEN BLOB DEFAULT NULL, ESANIMALES TINYINT(1) DEFAULT NULL, PRIMARY KEY(CODFAMILIA)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE fp (CODFP INT AUTO_INCREMENT NOT NULL, NOMBRE VARCHAR(40) DEFAULT NULL, NPLAZOS INT DEFAULT NULL, DISTANCIA INT DEFAULT NULL, CODEEMPRESA SMALLINT DEFAULT NULL, PRIMARY KEY(CODFP)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE marca (CODMARCA INT AUTO_INCREMENT NOT NULL, NOMBREMARCA VARCHAR(40) DEFAULT NULL, RUTALOGO VARCHAR(80) DEFAULT NULL, PRIMARY KEY(CODMARCA)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE origengasto (CODORIGEN INT AUTO_INCREMENT NOT NULL, DESCRIPCION VARCHAR(40) DEFAULT NULL, CUENTA VARCHAR(9) DEFAULT NULL, ESINMOLIZADO TINYINT(1) DEFAULT NULL, PRIMARY KEY(CODORIGEN)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE proveedor (CODPROVEEDOR INT AUTO_INCREMENT NOT NULL, RAZONSOCIAL VARCHAR(50) DEFAULT NULL, NIF VARCHAR(9) DEFAULT NULL, DOMICILIO VARCHAR(55) DEFAULT NULL, CODPOSTAL VARCHAR(10) DEFAULT NULL, POBLACION VARCHAR(30) DEFAULT NULL, PROVINCIA VARCHAR(30) DEFAULT NULL, EMAIL VARCHAR(60) DEFAULT NULL, WWW VARCHAR(70) DEFAULT NULL, TFNO1 VARCHAR(20) DEFAULT NULL, TFNO2 VARCHAR(20) DEFAULT NULL, FAX VARCHAR(20) DEFAULT NULL, MOVIL VARCHAR(20) DEFAULT NULL, CUENTA VARCHAR(9) DEFAULT NULL, CUENTAPAGO VARCHAR(9) DEFAULT NULL, IVAPERCENT NUMERIC(4, 2) DEFAULT NULL, AB VARCHAR(1) DEFAULT NULL, CODPAIS_OFICIAL VARCHAR(2) DEFAULT NULL, NIFPAISRESIDENCIA VARCHAR(20) DEFAULT NULL, CLAVEIDENPAISRESIDENCIA VARCHAR(2) DEFAULT NULL, CONTAB_INTRACOM SMALLINT DEFAULT NULL, TIENE_RE TINYINT(1) DEFAULT NULL, ESINVERSIONSUJETOPASIVO INT DEFAULT NULL, PAIS VARCHAR(20) DEFAULT NULL, CODFP INT DEFAULT NULL, TIPOGASTO INT DEFAULT NULL, INDEX PROVEEDOR_FK (CODFP), INDEX CAJ_PROV_FK (TIPOGASTO), PRIMARY KEY(CODPROVEEDOR)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE subfamilia (CODSUBFAMILIA INT NOT NULL, NOMBRE VARCHAR(40) DEFAULT NULL, IMAGEN BLOB DEFAULT NULL, CODFAMILIA INT NOT NULL, INDEX IDX_150B6A80C6BB373F (CODFAMILIA), PRIMARY KEY(CODSUBFAMILIA, CODFAMILIA)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE articulo ADD CONSTRAINT FK_69E94E915AC28B13 FOREIGN KEY (CODPROVEEDOR) REFERENCES proveedor (CODPROVEEDOR)');
        $this->addSql('ALTER TABLE articulo ADD CONSTRAINT FK_69E94E91D64BE6C2C6BB373F FOREIGN KEY (CODSUBFAMILIA, CODFAMILIA) REFERENCES subfamilia (CODSUBFAMILIA, CODFAMILIA)');
        $this->addSql('ALTER TABLE articulo ADD CONSTRAINT FK_69E94E91E8657820 FOREIGN KEY (CODMARCAR) REFERENCES marca (CODMARCA)');
        $this->addSql('ALTER TABLE proveedor ADD CONSTRAINT FK_16C068CEA0DD0184 FOREIGN KEY (CODFP) REFERENCES fp (CODFP)');
        $this->addSql('ALTER TABLE proveedor ADD CONSTRAINT FK_16C068CEBD8B63A5 FOREIGN KEY (TIPOGASTO) REFERENCES origengasto (CODORIGEN)');
        $this->addSql('ALTER TABLE subfamilia ADD CONSTRAINT FK_150B6A80C6BB373F FOREIGN KEY (CODFAMILIA) REFERENCES familia (CODFAMILIA)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE articulo DROP FOREIGN KEY FK_69E94E915AC28B13');
        $this->addSql('ALTER TABLE articulo DROP FOREIGN KEY FK_69E94E91D64BE6C2C6BB373F');
        $this->addSql('ALTER TABLE articulo DROP FOREIGN KEY FK_69E94E91E8657820');
        $this->addSql('ALTER TABLE proveedor DROP FOREIGN KEY FK_16C068CEA0DD0184');
        $this->addSql('ALTER TABLE proveedor DROP FOREIGN KEY FK_16C068CEBD8B63A5');
        $this->addSql('ALTER TABLE subfamilia DROP FOREIGN KEY FK_150B6A80C6BB373F');
        $this->addSql('DROP TABLE articulo');
        $this->addSql('DROP TABLE familia');
        $this->addSql('DROP TABLE fp');
        $this->addSql('DROP TABLE marca');
        $this->addSql('DROP TABLE origengasto');
        $this->addSql('DROP TABLE proveedor');
        $this->addSql('DROP TABLE subfamilia');
    }
}
